@startuml
hide methods

!include ApplicationUser.puml
!include Cliente.puml
!include MetodoPago.puml
!include Impresora3D.puml
!include TipoImpresora.puml
!include ReservaImpresora.puml
!include LineaReserva.puml
!include TiempoReserva.puml

Cliente "1" -- "0..*" ReservaImpresora : realiza
ReservaImpresora "1" *-- "1..*" LineaReserva : contiene
LineaReserva "0..*" --> "1" Impresora3D : impresora

@enduml