@startuml
class ReservaImpresora {
    + Id : int <<get>> <<set>>
    + FechaReserva : DateTime <<get>> <<set>>
    + NombreCliente : string <<get>> <<set>>
    + ApellidosCliente : string <<get>> <<set>>
    + DireccionFacturacion : string <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + MetodoPago : MetodoPago <<get>> <<set>>
    + ClienteId : string <<get>> <<set>>
    + Cliente : Cliente <<get>> <<set>>
}
@enduml
